spreadsheet: "https://docs.google.com/spreadsheets/d/1TcxzSeq5qWPkDVFQ5tZStXFY8ehOCnD-yqhuQrQvRcw/edit?gid=0"
spreadsheet_scratch: "https://docs.google.com/spreadsheets/d/1KaDWsUcnYQdiCQ5qFqXOjSTpuEupEN1rhV-8agFxptk/edit?gid=0"
spreadsheet_test: "https://docs.google.com/spreadsheets/d/1b6XSg-6a0X5NxH6GFTH3evEdwuZbUNYjjOfZ5akvKLA/edit?gid=0"

dataset:
  name: "hdx-hapi-operational-presence"
  title: "HDX HAPI - Coordination & Context: Operational Presence"
  tags:
    - "operational presence"
    - "who is doing what and where-3w-4w-5w"
  resource:
    name: "Global Coordination & Context: Operational Presence"
    description: "Operational Presence data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/coordination_and_context/#operational-presence) for more information"
    filename: "hdx_hapi_operational_presence_global.csv"
    headers:
      - "location_code"
      - "has_hrp"
      - "in_gho"
      - "provider_admin1_name"
      - "provider_admin2_name"
      - "admin1_code"
      - "admin1_name"
      - "admin2_code"
      - "admin2_name"
      - "admin_level"
      - "org_acronym"
      - "org_name"
      - "org_type_description"
      - "sector_code"
      - "sector_name"
      - "reference_period_start"
      - "reference_period_end"
      - "dataset_hdx_id"
      - "resource_hdx_id"
      - "warning"
      - "error"

org_dataset:
  name: "hdx-hapi-organisations"
  title: "HDX HAPI - Coordination & Context: Organisations"
  tags:
    - "operational partners"
  resource:
    name: "Global Coordination & Context: Organisations"
    description: "Organisation data from HDX HAPI"
    filename: "hdx_hapi_organisations_global.csv"
    headers:
      - "acronym"
      - "name"
      - "org_type_code"
      - "org_type_description"

dataseries_ignore:
  - "Fields Data - Operational Presence"

tags_ignore:
  - "climate hazards"
  - "climate-weather"
  - "complex emergency-conflict-security"
  - "conflict-violence"
  - "cyclones-hurricanes-typhoons"
  - "disease"
  - "drought"
  - "earthquake-tsunami"
  - "epidemics-outbreaks"
  - "flooding-storm surge"
  - "hazards and risk"
  - "natural disasters"

words_ignore:
  - "testing"
  - "district"
  - "province"
  - "region"
  - "northeast"

allowed_formats:
  - "csv"
  - "ods"
  - "tsv"
  - "xls"
  - "xlsx"

org:
  url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vSfBWvSu3fKA743VvHtgf-pIGkYH7zhy-NP7DZgEV9_a6YU7vtCeWhbLM56aUL1iIfrfv5UBvvjVt7B/pub?gid=1236872623&single=true&output=csv"

data_dictionary:
  - field: location_code
    label: Location code
    data_type: text
    description: "Location code based on ISO 3166 alpha-3 standard"
  - field: has_hrp
    label: Has hrp
    data_type: text
    description: "True if country has Humanitarian Response Plan"
  - field: in_gho
    label: In gho
    data_type: text
    description: "True if country is in Global Humanitarian Overview"
  - field: provider_admin1_name
    label: Provider admin1 name
    data_type: text
    description: "Original source admin-1 division name"
  - field: provider_admin2_name
    label: Provider admin2 name
    data_type: text
    description: "Original source admin-2 division name"
  - field: admin1_code
    label: Admin 1 code
    data_type: text
    description: "Admin 1 p-code from CODs (Common Operational Datasets)"
  - field: admin1_name
    label: Admin 1 name
    data_type: text
    description: "Admin 1 name from CODs, or original data source"
  - field: admin2_code
    label: Admin 2 code
    data_type: text
    description: "Admin 2 p-code from CODs (Common Operational Datasets)"
  - field: admin2_name
    label: Admin 2 name
    data_type: text
    description: "Admin 2 name from CODs, or original data source"
  - field: admin_level
    label: Admin level
    data_type: numeric
    description: "Administrative level (0-2)"
  - field: org_acronym
    label: Organization acronym
    data_type: text
    description: "Organization acronym"
  - field: org_name
    label: Organization name
    data_type: text
    description: "Organization name"
  - field: org_type_description
    label: Organization type description
    data_type: text
    description: "Description of organization type"
  - field: sector_code
    label: Sector code
    data_type: text
    description: "Sector code based on Global Coordination Groups dataset"
  - field: sector_name
    label: Sector name
    data_type: text
    description: "Name of sector"
  - field: reference_period_start
    label: Reference period start
    data_type: "timestamp without time zone"
    description: "Start date for which data are applicable"
  - field: reference_period_end
    label: Reference period end
    data_type: "timestamp without time zone"
    description: "End date for which data are applicable"
  - field: dataset_hdx_id
    label: Dataset HDX ID
    data_type: text
    description: "Unique dataset UUID on HDX"
  - field: resource_hdx_id
    label: Resource HDX ID
    data_type: text
    description: "Unique resource UUID on HDX"
  - field: warning
    label: Warning
    data_type: text
    description: "Set when correction was made to row's data"
  - field: error
    label: Error
    data_type: text
    description: "Set when row's data is incomplete or unusable"
