spreadsheet: "https://docs.google.com/spreadsheets/d/1TcxzSeq5qWPkDVFQ5tZStXFY8ehOCnD-yqhuQrQvRcw/edit?gid=0"
spreadsheet_scratch: "https://docs.google.com/spreadsheets/d/1KaDWsUcnYQdiCQ5qFqXOjSTpuEupEN1rhV-8agFxptk/edit?gid=0"
spreadsheet_test: "https://docs.google.com/spreadsheets/d/1b6XSg-6a0X5NxH6GFTH3evEdwuZbUNYjjOfZ5akvKLA/edit?gid=0"

dataset:
  name: "hdx-hapi-operational-presence"
  title: "HDX HAPI - Coordination & Context: Operational Presence"
  tags:
    - "hxl"
    - "operational presence"
    - "who is doing what and where-3w-4w-5w"
  resource:
    name: "Global Coordination & Context: Operational Presence"
    description: "Operational Presence data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/coordination_and_context/#operational-presence) for more information"
    filename: "hdx_hapi_operational_presence_global.csv"
    headers:
      - "location_code"
      - "has_hrp"
      - "in_gho"
      - "provider_admin1_name"
      - "provider_admin2_name"
      - "admin1_code"
      - "admin1_name"
      - "admin2_code"
      - "admin2_name"
      - "admin_level"
      - "org_acronym"
      - "org_name"
      - "org_type_description"
      - "sector_code"
      - "sector_name"
      - "reference_period_start"
      - "reference_period_end"
      - "dataset_hdx_id"
      - "resource_hdx_id"
      - "warning"
      - "error"

org_dataset:
  name: "hdx-hapi-organisations"
  title: "HDX HAPI - Coordination & Context: Organisations"
  tags:
    - "hxl"
    - "operational partners"
  resource:
    name: "Global Coordination & Context: Organisations"
    description: "Organisation data from HDX HAPI"
    filename: "hdx_hapi_organisations_global.csv"
    headers:
      - "acronym"
      - "name"
      - "org_type_code"
      - "org_type_description"

dataseries_ignore:
  - "Fields Data - Operational Presence"

tags_ignore:
  - "climate hazards"
  - "climate-weather"
  - "complex emergency-conflict-security"
  - "conflict-violence"
  - "cyclones-hurricanes-typhoons"
  - "disease"
  - "drought"
  - "earthquake-tsunami"
  - "epidemics-outbreaks"
  - "flooding-storm surge"
  - "hazards and risk"
  - "natural disasters"

words_ignore:
  - "testing"
  - "district"
  - "province"
  - "region"
  - "northeast"

allowed_formats:
  - "csv"
  - "ods"
  - "tsv"
  - "xls"
  - "xlsx"

org:
  url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vSfBWvSu3fKA743VvHtgf-pIGkYH7zhy-NP7DZgEV9_a6YU7vtCeWhbLM56aUL1iIfrfv5UBvvjVt7B/pub?gid=1236872623&single=true&output=csv"
